In [1]:
import tensorflow as tf

In [ ]:
# 타입 지정해주기(더블형은 float64)

In [3]:
a = tf.constant(3.0, tf.float32)

In [4]:
b = tf.constant(4.0, tf.float32)

In [ ]:
#상수를 이용한 add

In [5]:
x = tf.add(a, b)

In [ ]:
#1차원 배열을 이용한 add

In [8]:
import tensorflow as tf

In [9]:
a = tf.constant([5], dtype = tf.float32)

In [10]:
b = tf.constant([10], dtype = tf.float32)

In [17]:
c = tf.constant([4], dtype = tf.float32)

In [18]:
d = a * b + c # 배열을 일반 숫자처럼 연산?

In [21]:
print(d)

Tensor("add_4:0", shape=(1,), dtype=float32)


In [19]:
sess = tf.Session()

In [20]:
sess.run(d)

array([54.], dtype=float32)

In [24]:
print(sess.run(d))

[54.]


In [23]:
print(sess.run(tf.rank(d)))

1


In [22]:
print(d.shape)

(1,)


### 2차원 데이터의 연산

In [25]:
import tensorflow as tf

In [29]:
# 파이썬의 리스트를 넣어서 constant를 만들 수 있다!

In [27]:
a = tf.constant([2, 3]) # 1차원에 요소가 2개

In [33]:
b = tf.constant([[0, 1], [2, 3]]) # 2차원에 요소 2개

In [34]:
x = tf.add(a, b) # 연산이 가능한 이유 : a가 broad casting을 하기 때문. (게산을 하기 위해 ([2,3])이 ([2,3],[2,3]))이 됨.

In [35]:
y = tf.multiply(a, b)

In [36]:
sess = tf.Session()

In [37]:
print(sess.run(x))

[[2 4]
 [4 6]]


In [38]:
print(sess.run(y))

[[0 3]
 [4 9]]


In [39]:
print(sess.run(tf.rank(x)))

2


In [40]:
print(sess.run(tf.rank(y)))

2


In [41]:
print(x.shape)

(2, 2)


In [42]:
print(y.shape)

(2, 2)


### matrix multiply 

In [47]:
a = tf.constant([[2, 2]]) # 2차원

In [48]:
b = tf.constant([[0, 1], [2, 3]]) # 2차원

In [49]:
z = tf.matmul(a, b) # matrix 곱

In [50]:
sess.run(z) # 결과값?

array([[4, 8]])

In [54]:
print(sess.run(tf.rank(z)))

2


In [52]:
print(sess.run(tf.rank(b)))

2


In [66]:
print(z.shape)

(3, 2)


In [67]:
a = tf.constant(2)

In [69]:
b = tf.constant([[3],[2],[1]])

In [70]:
z = tf.multiply(a, b)

In [71]:
sess.run(z)

array([[6],
       [4],
       [2]])

In [56]:
a = tf.constant(2)

In [77]:
b = tf.constant([[1, 6], [3, 4], [6, 2]]) #3행 2열 (열 갯수만큼 대가로)

In [78]:
z = tf.multiply(a, b)

In [79]:
sess.run(z)

array([[ 2, 12],
       [ 6,  8],
       [12,  4]])

In [80]:
a = tf.constant([[1, 6],[3, 4],[5, 2]])

In [81]:
b = tf.constant([[1, -1], [2, 1]])

In [82]:
z = tf.matmul(a, b)

In [83]:
sess.run(z)

array([[13,  5],
       [11,  1],
       [ 9, -3]])

In [84]:
a = tf.constant([[3, 2, 1]])

In [85]:
b = tf.constant([[1],[3],[5]])

In [86]:
z = tf.matmul(a, b)

In [87]:
sess.run(z)

array([[14]])

In [89]:
a = tf.constant([[1],[3],[5]])

In [90]:
b = tf.constant([[1, 2]])

In [91]:
z = tf.matmul(a, b)

In [92]:
sess.run(z)

array([[ 1,  2],
       [ 3,  6],
       [ 5, 10]])

In [ ]:
#rank 쉽게 부르는 function

In [106]:
def printRank(code):
    import tensorflow as tf
    sess = tf.Session()
    print(sess.run(tf.rank(code)))

In [ ]:
#shape 쉽게 부르는 function

In [108]:
def printShape(code):
    print(code.shape)

In [107]:
printRank(z)

2


In [109]:
printShape(z)

(3, 2)
