In [68]:
import tensorflow as tf

In [104]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [105]:
col = 4

In [106]:
X = tf.placeholder(tf.float32, shape=[None, col])
Y = tf.placeholder(tf.float32, shape=[None, 3])

In [107]:
W = tf.Variable(tf.truncated_normal([col, 3]), name='weight')
b = tf.Variable(tf.truncated_normal([3]), name='bias')

In [108]:
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

In [109]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))

In [110]:
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [111]:
sess = tf.Session()

In [112]:
init = tf.global_variables_initializer()

In [113]:
sess.run(init)

In [114]:
for step in range(2001) :
    _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
    
    if step % 200 == 0 :
            print(step, cost_val)
    

0 6.320135
200 0.5719595
400 0.45924714
600 0.36181936
800 0.27074948
1000 0.23088259
1200 0.2092194
1400 0.19121674
1600 0.17600253
1800 0.16297346
2000 0.15169296


In [116]:
a = sess.run(hypothesis, feed_dict={X :[[1, 11, 7, 9]]})
print(a, sess.run(tf.argmax(a, 1)))

[[2.6783803e-03 9.9731284e-01 8.7981016e-06]] [1]


In [118]:
b = sess.run(hypothesis, feed_dict={X :[[1, 3, 4, 3]]})
print(b, sess.run(tf.argmax(b, 1)))

[[0.8988986  0.09222307 0.00887826]] [0]


In [119]:
c = sess.run(hypothesis, feed_dict={X :[[1, 1, 0, 1]]})
print(c, sess.run(tf.argmax(c, 1)))

[[1.0411912e-08 3.2175542e-04 9.9967825e-01]] [2]
