### Session 사용방법
###### 1) session 객체를 이용하는 방법 -> close() 해야함

In [44]:
import tensorflow as tf

In [45]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [46]:
z = tf.matmul(x, y)

In [47]:
sess = tf.Session()

In [48]:
print(sess.run(z, feed_dict={x : [[3., 3.], [3., 3.]], y : [[5., 5.], [5.,5.]]}))

[[30. 30.]
 [30. 30.]]


In [49]:
sess.close()

###### 2) with를 이용한 session 객체의 사용

In [50]:
import tensorflow as tf

In [51]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [52]:
z = tf.matmul(x, y)

In [65]:
with tf.Session() as sess :
    print(sess.run(z, feed_dict={x : [[3., 3.], [3., 3.]], y : [[5., 5.], [5.,5.]]}))

[[30. 30.]
 [30. 30.]]


###### InteractiveSession()
* run()을 하지 않고 eval()을 통해 바로 실행가능.

In [54]:
import tensorflow as tf

In [55]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [56]:
z = tf.matmul(x, y)

In [62]:
sess = tf.InteractiveSession()

In [67]:
print(z.eval(feed_dict={x : [[3., 3.], [3., 3.]], y : [[5., 5.], [5.,5.]]}))

[[30. 30.]
 [30. 30.]]


In [68]:
sess.close()

In [70]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [73]:
sess = tf.InteractiveSession()

In [99]:
data1 = tf.random_normal([100000]).eval() # 정규분포

In [ ]:
plt.hist(data1, bins=1000)

In [101]:
plt.show()

In [107]:
data2 = tf.random_uniform([100000000]).eval() # 0보다 큰 데이터를 랜덤으로 생성

In [112]:
data2

array([0.78621376, 0.4023161 , 0.3429451 , ..., 0.6931683 , 0.96581125,
       0.72475576], dtype=float32)

In [ ]:
plt.hist(data2, bins=100)