In [3]:
import numpy as np

In [6]:
import tensorflow as tf

### axis

In [1]:
# 1차원 : 열 -> axis => 0
# 2차원 : 행 -> axis => 0, 열 -> axis => 1
# 3차원 : 면 -> axis => 0, 행 -> axis => 1, 열 -> axis => 2

### axis의 고찰

In [13]:
# axis 3개 생성됨
# ndim = 3
# shape = 2, 4, 3

myary = np.array(
    [
        [
            [1, 2, 3],        #[ 0,0,0   0,0,1   0,0,2 ]
            [11, 12, 13],     #[ 0,1,0   0,1,1   0,1,2]
            [21, 22, 23],     #[ 0,2,0   0,2,1   0,2,2]
            [31, 32, 33]      #[ 0,3,0   0,3,1   0,3,2]
        ],
        [
            [1, 2, 3],        #[ 1,0,0   1,0,1   1,0,2]
            [11, 12, 13],     #[ 1,1,0   1,1,1   1,1,2]
            [21, 22, 23],     #[ 1,2,0   1,2,1   1,2,2]
            [31, 32, 33]      #[ 1,3,0   1,3,1   1,3,2]
        ]
    ]
)

In [6]:
print("myary 차원 : {}, shape : {}".format(myary.ndim, myary.shape))

myary 차원 : 3, shape : (2, 4, 3)


In [5]:
np.sum(myary)   # 모든 요소의 합

408

In [10]:
np.sum(myary, axis = 0)     # axis = 0 요소의 합

array([[ 2,  4,  6],
       [22, 24, 26],
       [42, 44, 46],
       [62, 64, 66]])

In [11]:
np.sum(myary, axis = 1)    # axis = 1 요소의 합

array([[64, 68, 72],
       [64, 68, 72]])

In [12]:
np.sum(myary, axis = 2)    # axis = 2 요소의 합

array([[ 6, 36, 66, 96],
       [ 6, 36, 66, 96]])

### Ndarray 생성방법

In [10]:
# 1)numpy
np.array([2,3,4])

array([2, 3, 4])

In [ ]:
# 2) tensorflow
# tf에서는 따로 Ndarray를 만드는 방법이 없다. 그래서 np를 이용하거나 파이썬을 이용해야 함.

### Transpose(전치행렬) 구하기
##### 전치행렬 = 대각선 기준으로 대칭하여 바꾸면 됨

In [7]:
# 1)numpy
x = np.array([[1,2],[3,4]], dtype = np.int8)
y = x.T

In [8]:
x

array([[1, 2],
       [3, 4]], dtype=int8)

In [9]:
y

array([[1, 3],
       [2, 4]], dtype=int8)

In [14]:
# 2) tensorflow
t = np.arange(24).reshape(4,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [21]:
t1 = t.transpose(1,2,0)
t1

array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [22]:
t1 = t.transpose(2,1,0)
t1

array([[[ 0,  6, 12, 18],
        [ 3,  9, 15, 21]],

       [[ 1,  7, 13, 19],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]]])

##### 직접 원소를 입력해서 다차원 배열 생성하기

###### 다차원배열 생성-1

In [27]:
# (1) bool
boolArray = np.array([True, False, True, True, False])
boolArray

array([ True, False,  True,  True, False])

In [28]:
boolArray.dtype

dtype('bool')

In [29]:
# (2) number
intArray = np.array([[1, 2],[3, 4]])
intArray

array([[1, 2],
       [3, 4]])

In [30]:
intArray.dtype 

dtype('int32')

In [31]:
# (3) 실수형
floatArray = np.array([[1.1, 2.2], [3.3, 4.4]])
floatArray

array([[1.1, 2.2],
       [3.3, 4.4]])

In [32]:
floatArray.dtype

dtype('float64')

In [33]:
floatArray2 = np.array([[1, 2], [3, 4]], dtype='float64')
floatArray2

array([[1., 2.],
       [3., 4.]])

In [34]:
floatArray2.dtype

dtype('float64')

In [35]:
#표준 코딩방법
floatArray3 = np.array([[1., 2.], [3., 4.]])
floatArray3

array([[1., 2.],
       [3., 4.]])

In [36]:
floatArray3.dtype

dtype('float64')

###### 다차원배열 생성-2

In [37]:
import numpy
numpy.empty

<function numpy.empty>

In [38]:
np.empty((4,3))

array([[1.00051107e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.08611944e-033],
       [9.41926725e-047, 1.03979713e-042, 7.78259174e-071],
       [5.93016835e-062, 1.16066580e-046, 2.00331593e-076]])

In [39]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.empty_like(A) 

array([[2066225168,        471, 1886216568],
       [ 175334764,  538976288,  757935405],
       [ 757935405,  538976266, 1044266528]])

In [41]:
b = np.zeros((2, 3))

In [42]:
b.dtype       # 기본 타입 = float

dtype('float64')

In [43]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
c = np.ones((2, 3))
c.dtype

dtype('float64')

In [46]:
d = np.ones((2,3), dtype = int)

In [47]:
d.dtype

dtype('int32')

In [48]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
np.identity(2)    # 단위행렬 만들기

array([[1., 0.],
       [0., 1.]])

In [50]:
np.identity(3, dtype=int)    # 대각서에 1을, 그 외에는 0을 가지는 2차원 배열

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [51]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [52]:
np.eye(3, 4, 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
np.eye(3, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [54]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [55]:
10 * np.ones((2,3), dtype = int)    # 이 방법을 더 선호

array([[10, 10, 10],
       [10, 10, 10]])

##### numpyarrange
###### 지정된 간격 내에서 균등하게 간격을 둔 값

In [56]:
# default value
# start = 0
# step = 1
np.arange(10)    # 10 = stop 값. 무조건 step 단위로 start 이상 stop 미만의 값이 생성됨.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(start = 1.0, stop = 5.0, step = 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])