### 분류된 데이터 label이 2개 이상인 경우
- softmax()를 이용한다.

In [60]:
import tensorflow as tf

In [61]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [62]:
col = 4

In [63]:
X = tf.placeholder(tf.float32, shape=[None, col])
Y = tf.placeholder(tf.float32, shape=[None, 3])

In [64]:
w = tf.Variable(tf.truncated_normal([col, 3]), name='weight')
b = tf.Variable(tf.truncated_normal([3]), name='bias')

In [65]:
hypothesis = tf.nn.softmax(tf.matmul(X, w) + b)

In [66]:
cost = - tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

In [67]:
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

In [68]:
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)

In [69]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted , Y), dtype = tf.float32))

In [72]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    
    for step in range(5000) :
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
        
        if step % 200 == 0 :
            print(step, cost_val)
            
    hy_val, pre_val, acc_val = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    print('\nHypothesis : ', hy_val, '\nPredicted :', pre_val, '\nAccuracy : ', acc_val)

0 1.5354401
200 0.52195215
400 0.48001853
600 0.44729862
800 0.4224732
1000 0.4034495
1200 0.38844275
1400 0.37622532
1600 0.36599484
1800 0.35722065
2000 0.34954262
2200 0.3427094
2400 0.3365406
2600 0.33090428
2800 0.32570112
3000 0.32085574
3200 0.31630945
3400 0.31201622
3600 0.30793917
3800 0.30404884
4000 0.30032113
4200 0.29673645
4400 0.29327855
4600 0.28993365
4800 0.28669068

Hypothesis :  [[9.3514528e-03 3.3769593e-02 9.5687902e-01]
 [4.0449183e-03 1.6435553e-01 8.3159953e-01]
 [9.2992687e-04 3.7740156e-01 6.2166858e-01]
 [1.9979129e-04 6.7087597e-01 3.2892430e-01]
 [5.9256464e-01 3.1094578e-01 9.6489601e-02]
 [2.8958070e-01 7.0502657e-01 5.3926762e-03]
 [5.9965593e-01 3.8800660e-01 1.2337469e-02]
 [6.9671017e-01 3.0056888e-01 2.7209583e-03]] 
Predicted : [[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]] 
Accuracy :  0.9166667
